# shellcheck shell=bash

BRIDGE_MANAGED_CLUSTER_PUBLIC_URL=$(oc whoami --show-server)
export BRIDGE_MANAGED_CLUSTER_PUBLIC_URL

# BRIDGE_MANAGED_CLUSTER_BEARER_TOKEN=$(oc whoami --show-token)
# export BRIDGE_MANAGED_CLUSTER_BEARER_TOKEN

BRIDGE_MANAGED_CLUSTER_THANOS_URL=$(oc -n openshift-config-managed get configmap monitoring-shared-config -o jsonpath='{.data.thanosPublicURL}')
export BRIDGE_MANAGED_CLUSTER_THANOS_URL

BRIDGE_BASE_ADDRESS=http://localhost:9000
export BRIDGE_BASE_ADDRESS

BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS=true
export BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS

BRIDGE_K8S_AUTH=openshift
export BRIDGE_K8S_AUTH

BRIDGE_USER_AUTH=openshift
export BRIDGE_USER_AUTH

BRIDGE_USER_AUTH_OIDC_CLIENT_ID=multicluster-console
export BRIDGE_USER_AUTH_OIDC_CLIENT_ID

BRIDGE_CA_FILE=examples/ca.crt
export BRIDGE_CA_FILE

BRIDGE_USER_AUTH_OIDC_CA_FILE=examples/ca.crt
export BRIDGE_USER_AUTH_OIDC_CA_FILE

BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET_FILE=examples/console-client-secret
export BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET_FILE

echo "Using managed cluster $BRIDGE_MANAGED_CLUSTER_PUBLIC_URL"
